[colors.primary]
background = "#262626"
foreground = "#c0b18b"

[cursor]
blink_interval = 500
unfocused_hollow = false

[cursor.style]
blinking = "On"
shape = "Block"

[font]
size = 13.0
offset.x = 1 # For letter spacing (default: 0)
offset.y = 4  # For line spacing (default: 0)

[font.italic]
family = "JetBrains Mono"
style = "Italic"

[font.bold]
family = "JetBrains Mono"
style = "Light"

[font.normal]
family = "JetBrains Mono"
style = "Light"


[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[window]
decorations = "full"

[env]
TERM = "xterm-256color"
# Set horizontal splits to appear to the right
